package adts;

/**
 * Represents a sorted (ascending) list of elements. The list should grow
 * to accommodate any number of elements.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public interface IOrderedList<T extends Comparable<T>> extends ICollection<T>
{
    /**
     * Adds an element to the collection, while maintaining the order
     * of all elements in the collection. Elements should always be
     * in ascending order.
     *
     * @param element the element to add
     * @throws IllegalArgumentException if the input parameter cannot
     * be cast to the Comparable interface
     */
    void add(T element);

    /**
     * Returns an element at the specified index.
     *
     * @param index an index in the list
     * @return an element in the list at the given index
     * @throws IndexOutOfBoundsException if given a negative index or
     * an index greater or equal to size()
     */
    T get(int index);
}
