package adts;

/**
 * Represents a FILO Stack that can reverse the order of
 * elements in the stack. The size of the stack should
 * increase to support any number of elements.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public interface IReversibleStack<T> extends ICollection<T>
{
    /**
     * Reverses the order of all elements in the stack.
     * For example: (bottom) a, b, c, d (top) becomes
     *              (bottom) d, c, b, a (top) after
     *              calling reverse()
     */
    void reverse();

    /**
     * Removes, and returns, the top element of the stack.
     * @return the top element of the stack
     * @throws java.util.NoSuchElementException when the stack is empty
     */
    T remove();
}
